[project]
name = "automations"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "prefect>=3.4.20",
]

[uv.build]
package=true

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
